### CREATE opening
POST http://localhost:8080/api/v1/opening
Content-Type: application/json

{
  "role": "Senior Software Engineer",
  "company": "Tech Innovators Inc.",
  "location": "Londrina, PR",
  "remote": true,
  "link": "https://techinnovators.example.com/careers/12345",
  "salary": 30000
}

### GET opening by id
GET http://localhost:8080/api/v1/opening?id=3

### GET list of all openings
GET http://localhost:8080/api/v1/openings

### UPDATE request opening by id
PATCH http://localhost:8080/api/v1/opening?id=4
Content-Type: application/json

{
  "role": "Teste",
  "company": "Tech Innovators Inc.",
  "location": "Londrina, PR",
  "remote": true,
  "link": "https://techinnovators.example.com/careers/12345",
  "salary": 30000
}

### DELETE request opening
DELETE http://localhost:8080/api/v1/opening?id=3